version: "3.9"

services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - registry_data:/var/lib/registry

  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    image: backend:latest
    container_name: backend
    volumes:
      - db_data:/app
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
        python manage.py makemigrations dogs &&
        python manage.py migrate --noinput &&
        gunicorn app.wsgi:application --bind 0.0.0.0:8000
      "

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile 
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  registry_data:
  db_data: 